#!/bin/bash
eg=$1
benchmarkmodels=$2
testmodels=$3
set -e
if [ -z ${RMG_BENCHMARK+x} ]; then 
	echo "RMG variable is unset. Exiting..."
	exit 0
fi

export ORIGIN_PYTHONPATH=$PYTHONPATH
echo "Running $1 example"

###########
#BENCHMARK#
###########
# make folder for models generated by the benchmark version of RMG-Py/RMG-database:
mkdir -p tests/$benchmarkmodels/$eg
rm -rf tests/$benchmarkmodels/$eg/*
cp examples/rmg/$eg/input.py tests/$benchmarkmodels/$eg/input.py

source activate benchmark

echo "benchmark version of RMG: "$RMG_BENCHMARK
cd $RMG_BENCHMARK
git log --format=%H%n%cd -1
cd -

export PYTHONPATH=$RMG_BENCHMARK:$ORIGIN_PYTHONPATH 

# use the rmgrc file to point to the location of the desired RMG-database:
rmgrc="database.directory : "${RMGDB_BENCHMARK}/input/
rm -rf $HOME/.rmg
mkdir -p $HOME/.rmg
echo $rmgrc >> $HOME/.rmg/rmgrc

python $RMG_BENCHMARK/rmg.py tests/$benchmarkmodels/$eg/input.py > /dev/null

source deactivate
export PYTHONPATH=$ORIGIN_PYTHONPATH

#########
#TESTING#
#########
# make folder for models generated by the test version of RMG-Py and RMG-database:
mkdir -p tests/$testmodels/$eg
rm -rf tests/$testmodels/$eg/*
cp examples/rmg/$eg/input.py tests/$testmodels/$eg/input.py
source activate testing
echo "test version of RMG: "$RMG_TESTING
cd $RMG_TESTING
git log --format=%H%n%cd -1
cd -

export PYTHONPATH=$RMG_TESTING:$ORIGIN_PYTHONPATH 

# use the rmgrc file to point to the location of the desired RMG-database:
rmgrc="database.directory : "${RMGDB_TESTING}/input/
rm -rf $HOME/.rmg
mkdir -p $HOME/.rmg
echo $rmgrc >> $HOME/.rmg/rmgrc

python $RMG_TESTING/rmg.py tests/$testmodels/$eg/input.py > /dev/null
export PYTHONPATH=$ORIGIN_PYTHONPATH
source deactivate


# compare both generated models
source activate benchmark
export PYTHONPATH=$RMG_BENCHMARK:$ORIGIN_PYTHONPATH 

bash check.sh $eg tests/$benchmarkmodels/$eg tests/$testmodels/$eg

export PYTHONPATH=$ORIGIN_PYTHONPATH
source deactivate

# make folder for models generated by the test version of RMG-Py and RMG-database, with scoop enabled:
mkdir -p tests/$testmodels/$eg/scoop
rm -rf tests/$testmodels/$eg/scoop/*
cp examples/rmg/$eg/input.py tests/$testmodels/$eg/scoop/input.py
echo "Version of RMG running with SCOOP: $RMG"
source activate testing
export PYTHONPATH=$RMG_TESTING:$ORIGIN_PYTHONPATH

python -m scoop -n 1 $RMG_TESTING/rmg.py tests/$testmodels/$eg/scoop/input.py > /dev/null

export PYTHONPATH=$ORIGIN_PYTHONPATH
source deactivate

# compare both generated models
source activate benchmark
export PYTHONPATH=$RMG_BENCHMARK:$ORIGIN_PYTHONPATH 

bash check.sh $eg tests/$benchmarkmodels/$eg tests/$testmodels/$eg/scoop

export PYTHONPATH=$ORIGIN_PYTHONPATH
source deactivate